CREATE TABLE IF NOT EXISTS otps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id UUID NOT NULL UNIQUE,
    otp_code VARCHAR(6) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER set_created_at
AFTER UPDATE ON otps
BEGIN
    UPDATE otps SET created_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
